AssistantBot.Telegram/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AssistantBot.Telegram.Models
{
    public class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Question Question { get; set; }
        public int? QuestionId { get; set; }
    }
}

AssistantBot.Telegram/Models/Bot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Telegram.Bot;

namespace AssistantBot.Telegram.Models
{
    public static class Bot
    {
        private static string Token { get; }
        public static TelegramBotClient bot { get; }

        static Bot()
        {
            Token = "825644646:AAG5NpRzPEjtIuw2g0k_eo9Uv1B3NjufaBs";
            bot = new TelegramBotClient(Token);
        }
    }
}

AssistantBot.Telegram/Models/BotContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace AssistantBot.Telegram.Models
{
    public class BotContext: DbContext
    {
        public DbSet<Theme> Themes { get; set; } 
        public DbSet<Question> Questions { get; set; }
        public DbSet<Answer> Answers { get; set; }
    }
}

AssistantBot.Telegram/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AssistantBot.Telegram.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Theme Theme { get; set; }
        public int? ThemeId { get; set; }
        public ICollection<Answer> Answers { get; set; }

        public Question()
        {
            Answers = new List<Answer>();
        }
    }
}

AssistantBot.Telegram/Models/Theme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AssistantBot.Telegram.Models
{
    public class Theme
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Question> Questions { get; set; }

        public Theme()
        {
            Questions = new List<Question>();
        }
    }
}

AssistantBot.Telegram/Controllers/HomeController.cs
using AssistantBot.Telegram.Models;
using AssistantBot.Telegram.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Telegram.Bot;
using Telegram.Bot.Types.Enums;

namespace AssistantBot.Telegram.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            BotContext _db = new BotContext();
            botService service = new botService(_db);
            Task.Run(()=>service.startBot());
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Redaction()
        {
            return View();
        }
    }
}

AssistantBot.Telegram/Controllers/api/RedactionController.cs
using AssistantBot.Telegram.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AssistantBot.Telegram.Controllers.api
{
    public class RedactionController : ApiController
    {
        BotContext _db = new BotContext();

        // GET api/<controller>
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<controller>/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public void Delete(int id)
        {
        }

        [HttpGet]
        [Route("api/GetAllThemes")]
        public IEnumerable<Theme> GetAllThemes()
        {
            return _db.Themes;//.Select(n => n.Name);
        }
    }
}

AssistantBot.Telegram/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AssistantBot.Telegram/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AssistantBot.Telegram/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AssistantBot.Telegram/Views/Home/Redaction.cshtml
@{
    ViewBag.Title = "Редактирование";
}

<h2>Редактирование</h2>

<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Тема</th>
                <th scope="col">Вопрос</th>
                <th scope="col">Ответ</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

@section scripts{
<script>
    $(function () {
        $.ajax({
            method: 'GET',
            dataType: 'json',
            url: '/api/GetAllThemes',
            success: function (e) {
                //$.each(e, function (key, value){
                //    $('#ex').text(value.Name);
                //});

                //
                $.each(e, function (key, value) {
                    $('tbody').append(`
                    <tr>
                    <td>${key}</td>
                    <td>${value.Name}</td>
                    <td>${value.Name}</td>
                    </tr>
                `);
                });
               
                //
            }
        });
    });
</script>
}

AssistantBot.Telegram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Редактирование", "Redaction", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>